name: Android CI

on:
  push:
    branches:
      - 'develop'
      - 'release/*'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Update Run Number in properties
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: gradle.properties
          property: RUN_NUMBER
          value: ${{ github.run_number }}

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make .android folder
        run: mkdir /home/runner/.android

      - name: Create debug keystore
        run: |
          echo "${{ secrets.CI_KEYSTORE }}" > debug.keystore.asc
          gpg -d --passphrase "${{ secrets.CI_KEYSTORE_DECRYPT }}" --batch debug.keystore.asc > /home/runner/.android/debug.keystore
      - name: Build debug APK
        run: bash ./gradlew assembleCi --stacktrace

      - name: set apk name env
        run: echo "APK_NAME=$(basename app/build/outputs/apk/ci/*.apk .apk)" >> $GITHUB_ENV

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.APK_NAME }}
          path: app/build/outputs/apk/ci/${{ env.APK_NAME }}.apk

      - name: Upload to Discord
        uses: sinshutu/upload-to-discord@v2.0.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: app/build/outputs/apk/ci/${{ env.APK_NAME }}.apk
